language: node_js
node_js:
  - "6"
  - "8"
dist: trusty
sudo: false # better for performance

before_install:
  - TRAVIS=1 # used by build.sh
  - npm i -g npm@5.8.0

install:
  # Create file & folder for Travis logs
  # cfr scripts/_travis-fold.sh
  - mkdir -p $LOGS_DIR
  - touch $LOGS_DIR/build-perf.log
  - npm ci
  - npm run install:ci:all

env:
  global:
    - LOGS_DIR=/tmp/stark/logs
    - LOGS_FILE=/tmp/stark/logs/build-perf.log

branches:
  only:
  - master

cache:
  directories:
    - $HOME/.npm

# Not needed since we use Puppeteer in karma.conf.typescript.ci.js
# It downloads Chrome itself and works with or without Travis
#addons:
#  chrome: stable

script:
  - npm run lint:all
  - npm run test:ci:all
